#########################################################################################################################
## general configuration
#########################################################################################################################

verbose: True


#########################################################################################################################
## tools
#########################################################################################################################

fastqc:
  adapters: resources/ont/ont_adapters.fastqc.tsv

bbduk:
  default: t=4 pigz=t unpigz=t
  filtering: -Xmx2g qin=33 minlen=200 qtrim=lr trimq=10 maq=10 maxlen=100000

repeat_region_spanning:
  edit_distance: 2

